apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-shopping-deployment
  labels:
    app: google-shopping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: google-shopping
  template:
    metadata:
      labels:
        app: google-shopping
    spec:
      containers:
        - name: google-shopping
          image: <IMAGE_PLACEHOLDER>
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: google-shopping-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: google-shopping-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
